name: continuous integration
on: push 
env:
  dbname: test
  dbuser: root
  dbpassword: ID0ntknowdbms
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'ALTER USER "${{env.dbuser}}"@"localhost" IDENTIFIED BY "${{env.dbpassword}}";' -uroot -proot
          sudo mysql -e 'CREATE DATABASE ${{env.dbname}};' -u${{env.dbuser}} -p${{env.dbpassword}}
      - name: Checkout Repo Code
        uses: actions/checkout@v2 
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Run linting
        run: |
          go fmt ./... 
          go vet ./...
      - name: Run tests
        run: go test